### ISSUE TITLE
Feature: Shuffle water net

### ISSUE THREAD

**Issue by jeffreybardon** [Thedragon005/Archipelago-Ape-Escape#12]
### What feature would you like to see?

The logic for this is largely written and in place, this is primarily a client/option update.

See [these messages](https://discord.com/channels/731205301247803413/1168645708103028856/1281312594225008682) for some technical details.

Issue #13 should be done first.

**Comment by Thedragon005** [comment]
Tested the values for CanDive and CanWaterCatch

Works as expected,only changed once during connect and it stays. Will wait until we could implement CanSwim and then make a build with it.

**Comment by Thedragon005** [comment]
Got it working on `apeescape-swim` .

The only thing left is testing Generation with dofferent options to make sure it does not break

**Comment by jeffreybardon** [comment]
Generation has been tested with this on and some of the more restricted possible early games, including with entrance shuffle on. I encountered no failed generations, so this now just needs a bit more testing and a full seed played with it to be considered done.

**Comment by Thedragon005** [comment]
There has been fully played seeds with this functionality and no errors,can resolve this (#42)
