### ISSUE TITLE
Feature: Shuffle Time Net

### ISSUE THREAD

**Issue by jeffreybardon** [Thedragon005/Archipelago-Ape-Escape#13]
### What feature would you like to see?

The logic for this is entirely worked out but not implemented.
The client-side update should work similarly to random starting gadget.

Issue #6 should be resolved before implementing this.

**Comment by Thedragon005** [comment]
Could be added to starting gadget option as another choice for it by creating option "net_only" and changing "none" to be no Gadget at all

**Comment by Thedragon005** [comment]
As stated by IHNN in discord,there is solo generation fails when coins = off and Time net is shuffled.

He had an idea to fix it to add Mailboxes as locations.
Created issue #37

**Comment by Thedragon005** [comment]
Tested and working now with the addition of Mailboxes ! (#41)
