### ISSUE TITLE
Improvement: Find a way to send monkeys on catch instead of on room exit

### ISSUE THREAD

**Issue by jeffreybardon** [Thedragon005/Archipelago-Ape-Escape#14]
### What task needs to be completed?

Having monkeys only send on exiting a room doesn't feel good to play, compared to an instant or near-instant send.

A few issues that have come up already from the current behavior:
1. Retrieving a hinted item - heavy artificial delay on sending that item (especially notable in longer rooms)
2. Getting an item in a level with a single room (such as getting Flyer in Fossil Field or Sling in Snowy Mammoth) - can force re-entering the same level.
3. Getting an item in a multi-room level forces either an unnecessary transition to "check" the item, or exiting and potentially having to re-enter (Molten Lava with Sling comes up in every solo seed sphere 1)
4. Once filler items are implemented, the delay will prevent local cookies from restoring health mid-room.

**Comment by Thedragon005** [comment]
Agreed, there should be a way to write to memory to mimic a room transition on a monkey catch and update instantly with local RAM addresses

**Comment by Thedragon005** [comment]
Were able to find all local addresses and pushed some commits to ``apeescape-Dev-0.21``.
Put BETA `apeescape.apworld` into [discord thread](https://discord.com/channels/731205301247803413/1168645708103028856/1286132486610620416) for testing until Sunday

**Comment by jeffreybardon** [comment]
This was such a delight to finally have working when I did a test seed today, looks good.

**Comment by Thedragon005** [comment]
Can close as the latest release has no issue
