### ISSUE TITLE
Feature : Implement Filler items

### ISSUE THREAD

**Issue by jeffreybardon** [Thedragon005/Archipelago-Ape-Escape#15]
### What task needs to be completed?

The filler items currently behave as named Nothings.

This would need to be implemented in the client.

**Comment by jeffreybardon** [comment]
There's room for another task after this about balancing the amount of each type of filler item, as well as implementing special pellet maximum increases. It's even possible to start with a maximum of 0 of each special pellet type; though implementing this as an option may have some logical implementations, if regular pellets can't damage something.

**Comment by Thedragon005** [comment]
This belongs in "Stable Release" milestone. Fillers are still an important part of Gameplay so at least making them work as intended could be really good

**Comment by Thedragon005** [comment]
Working on this for the next days :)

**Comment by Thedragon005** [comment]
Implemented in #21 (Will open another issue later to balance their quantity)
