### ISSUE TITLE
Core: Implement checks on Crumbling Castle/TV Tower bosses

### ISSUE THREAD

**Issue by jeffreybardon** [Thedragon005/Archipelago-Ape-Escape#16]
### What task needs to be completed?

These currently do literally nothing for the multiworld. Making them locations would solve this.

The logic is already worked out, just needs implementing. The hard part is likely having the client check for these completions.

**Comment by Thedragon005** [comment]
Could also implement ways of including location checks for MM Professor,Nathalie and Jake for checks

Edit: I'll make a separate issue

**Comment by Thedragon005** [comment]
Changed in last pull #31

Waiting for last corrections before making release

**Comment by jeffreybardon** [comment]
Looks good to me as of latest Discord beta apworld.

**Comment by Thedragon005** [comment]
Latest release have both bosses as locations and it works each time.

I can close this issue

**Comment by Thedragon005** [comment]
There is still a bug that happens when you enter/exit TVT Boss room that gives you the check even worhout defeating the boss.

**Comment by jeffreybardon** [comment]
The aforementioned bug has been fixed.
