### ISSUE TITLE
Improvement : Change the way Specter fights completion are detected

### ISSUE THREAD

**Issue by Thedragon005** [Thedragon005/Archipelago-Ape-Escape#23]
### What feature would you like to see?

If the fight with both Specter's sent the check on final hit, it would feel more responsive for both goals. (S1 and S2)

It could also mean we could try to skip the cutscenes without affecting the sending of the locations.

Chocobo13 said some addresses could be checked for better Specters detections (Start of conversation) :
https://discord.com/channels/731205301247803413/1168645708103028856/1283937821257629746

(Talking about Specter 1)
2 main messages :
Specter mech health value seems to be stored at 0x80144a06

The byte after it, 0x80144a07, also becomes 3 once that phase begins, so I think we can check to see if the player is in that room, if that byte is then 3, and if the health hits 0, then it should count

**Comment by Thedragon005** [comment]
Changed in last pull #31

Waiting for last corrections before making release

**Comment by jeffreybardon** [comment]
Looks good to me as of latest Discord apworld.

**Comment by Thedragon005** [comment]
Latest release got both specters register on last hit,works as intended. I can close this
