### ISSUE TITLE
Bug: Completing the last currently unlocked level will unlock the next level, regardless of world keys

### ISSUE THREAD

**Issue by jeffreybardon** [Thedragon005/Archipelago-Ape-Escape#25]
### What happened?

For example, if you fully complete Molten Lava, Thick Jungle will be opened up even though it's only supposed to open after getting 1 World Key.

### What were the expected results?

Levels only unlock from World Keys.

**Comment by Thedragon005** [comment]
See issue in CDRomatron branch and proposed solution:
https://github.com/CDRomatron/Archipelago-Ape-Escape/issues/41
> A possible fix could be to set the level state as 2 whilst in these levels, however I'm unsure if this would stop the 8-3 from progressing you

Could work.

For 8-3 it could check hundo monkeys address to lock/unlock the next level

**Comment by Thedragon005** [comment]
Fix in progress on branch ``apeescape-dev``
Will be `testing` tonight

**Comment by Thedragon005** [comment]
**Still in testing** 

Progress:
Levels not adjacent to Dimension X levels works now.

Applied a fix for 5-3 to prevent being kicked-out if catching all monkeys (Would get you instantly into GA,which we want to avoid)

Need to test for 2-3 to see if same fix can be applied or if there is even a problem for SA access (IIRC 2-3 does not kick you out to SA but instead to Time Hub)

**Comment by Thedragon005** [comment]
Can close as the latest release has no issue
