### ISSUE TITLE
Feature: Prevent automatic level ejections after catching all monkeys in a level

### ISSUE THREAD

**Issue by jeffreybardon** [Thedragon005/Archipelago-Ape-Escape#33]
### What feature would you like to see?

The current behavior feels more like a bug than anything: the last monkey in a level will only eject you sometimes, seemingly correlated to whether or not the next world is currently unlocked. Considering this shows that it's possible to avoid auto-ejections, this would be the ideal behavior for catching the last monkey in any level, as it puts full control of when you exit a level in your hands. Boss levels auto-ejecting are fine since the boss is there as a clear end.

Levels where the early ejection are very unfortunate include Thick Jungle (mushroom area coin), Hot Springs (either coin can be problematic), Sushi Temple (well coin), Wabi Sabi Wall (final room coin), and more.

The desired behavior is to just never eject the player after catching a monkey.

**Comment by Thedragon005** [comment]
Got a WIP build at the moment (See last Pin in the Discord [thread](https://discord.com/channels/731205301247803413/1168645708103028856/1290033042144104508)).
Tested all 21 levels while they are in the "Completed" state
Tested again by hardcoding the keys to be locked in the current world, tested each x-3 levels

Not one I have been Kicked out.

-Note : Bosses will still kick you out, but to Time Hub. It may not be Critical to fix right now

**Comment by Thedragon005** [comment]
Can close as the latest release has no issue
