### ISSUE TITLE
Locations:  Add MM Nathalie,Prosessor and Jake check

### ISSUE THREAD

**Issue by Thedragon005** [Thedragon005/Archipelago-Ape-Escape#48]
### What feature would you like to see?

Two possibilities discussed in the discord : 
- Add them as locations AND items to prevent the MM Lobby door from opening
- Add them as Locations only, but this means in normal settings since they are mandatory the players would do it anyway. We could pre-open the door in that case

**Comment by jeffreybardon** [comment]
Merging into #50 as general Monkey Madness enhancements
