### ISSUE TITLE
Bug: Starting inventory ignored or not working

### ISSUE THREAD

**Issue by Thedragon005** [Thedragon005/Archipelago-Ape-Escape#6]
### What happened?

From discord IHNN(jeffreybardon) : 
When adding an item to start_inventory,it appears in Archipelago but not in-game

### What were the expected results?

It seems harcoded,it should fetch from Archilelago room directly and have the Item appear in game as well

### Software

While playing

**Comment by jeffreybardon** [comment]
Expanding on this, the issue is that the client does not check for the contents of start inventory when syncing items. Should be pretty simple to fix.

**Comment by jeffreybardon** [comment]
In the client, ctx.items_handling was set to 0b011. This explicitly does not send starting inventory. Fixed and closing.
