### ISSUE TITLE
Bug: Specter's does not register sometimes/when not in goal

### ISSUE THREAD

**Issue by Thedragon005** [Thedragon005/Archipelago-Ape-Escape#8]
### What happened?

From discord :
Riekelt
I've played a seed myself yesterday, went for PPM as ending

Opened when I expected it
I got ejected all the time when expected
I'm missing the same 5 monkeys, HOWEVER, instead of 9-1 I'm missing 9-2. Seeing how it's both specter, unsure?

![image](https://github.com/user-attachments/assets/ab9ebd03-04c0-4893-b220-6a1cca8b9f52)

### What were the expected results?

It should clear the location accordingly

### Software

While playing

**Comment by Thedragon005** [comment]
To elaborate on this : 

The locations seems not to be sending fully

If the goal is : 

- Specter 1 : it should not add Specter 2 to the locations. (Or remove it after)

- Specter 2 : Should still send the location to AP in addition to Victory

**Comment by Thedragon005** [comment]
As IHNN stated in discord, it seems Specter 1 Location sends correctly to AP after commit 75df881c782b7624d4ecd5eba8698d416adcc728
Still in testing.

**Comment by Thedragon005** [comment]
As IHNN stated in discord, it seems Specter 1 Location sends correctly to AP after commit https://github.com/Thedragon005/Archipelago-Ape-Escape/commit/75df881c782b7624d4ecd5eba8698d416adcc728
Still in testing.

**Comment by jeffreybardon** [comment]
Played a game with two other Ape Escape people today, Specter 1 sent for all three of us. Closing as done.
