### ISSUE TITLE
Core: Implement Location/Item Groups

### ISSUE THREAD

**Issue by jeffreybardon** [Thedragon005/Archipelago-Ape-Escape#9]
### What task needs to be completed?

Implementing location and item groups for meta-use. Stuff like being able to exclude_locations: Stadium Attack to automatically exclude all locations in that level, or start_hints: Gadgets to automatically hint all gadgets.

**Comment by Thedragon005** [comment]
Items groups that at minumum seems a good idea to implement : 
Gadgets : club,radar,sling,hoop,car,punch,flyer
Keys: All 6 keys
DimensionX : Stadium Attack and Gladiator Attack

**Comment by jeffreybardon** [comment]
I created the following groups:
Item Group: Gadgets
Location Groups: one for each level (21 levels - there isn't one for Peak Point Matrix), and one for Coins, Monkeys, Bosses, and the ever-requested Races.

I did not create an item group for keys because there's no point creating a group for a single item type - if we ever have by-level unlocking (so that, say, Molten Lava key is a thing) it's easy to add the group then, but for now it's unnecessary.
